config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :stdlib do
    get :chapters
    get :about
    get :team
    get :mobbing
    get :agile
    get :testing
    get :rgsoc
    get :userstories
    get :goals
  end

 namespace :chapters do
   get :http
   get :math
   get :time
   get :database
   get :encoding
   get :exceptions
   get :read
   get :dsl
   get :gui
   get :commandline
   get :patterns
   get :methods
   get :threads
   get :core
   get :objective2
   get :objective3
 end

  resources :adventures, only: []  do
    member do
      get :story
    end
    resources :objectives, only: [] do
      member do
        get :learn
        get :review
        post :repl
      end
    end
  end
  get '/prettyp' => 'status#prettyp'
end

app/models/adventure.rb
class Adventure
  attr_accessor :title, :introduction, :id
  def initialize(id, title, introduction)
    @id = id
    @title = title
    @introduction = introduction
  end
  def self.find(id)
    ADVENTURES.find { |value| value.id.to_i == id.to_i }
  end

  def ==(other)
    @title == other.title &&
    @introduction == other.introduction &&
    @id == other.id
  end

  ADVENTURE1_TEXT =
    <<-INTRODUCTION
Oh no! Cuddy runs ahead of Mr. Chips and fell down a well. There are snakes in the well. Cuddy finds a tin can with a string leading to the top of the well. He needs your help to place the call (he thinks the phone works). Let’s try to call Cuddy’s agent, PrettyP.
    INTRODUCTION
  ADVENTURES = [
    Adventure.new( '1', 'Adventure 1', ADVENTURE1_TEXT)
  ]

# assigns names to ids
  NETHTTP = 1
end

app/models/narrative.rb
class Narrative
  attr_accessor  :pair_id, :type, :copy, :image_url

  def initialize(adventure_id, objective_id, type, copy, image_url)
    @pair_id = { 
		adventure_id: adventure_id, 
		objective_id:  objective_id
		}
    @type = type
    @copy = copy
    @image_url = image_url
  end
NARRATIVES = [
  Narrative.new(Adventure::NETHTTP, Objective::GET_301, 'learn', "You just made a call to the web. You used a library from the Ruby Standard library called net/http to place a call on the web. By making the request you discover that the web page moved. What does this mean? Let’s break that down a bit... When Cuddy calls Pretty P. he can’t reach her because Pretty P. has moved to Hollywood. Just like if you call someone’s phone number who has moved; you would hear a disconnect message from the operator. The web has similar messages. A 301 Error means that the web page has moved. You are often re-directed to adifferent page without even seeing this error.",  'image_url'),
  Narrative.new(2, 1, 'submit', 'copy', 'image_url')
]
  def self.find(adventure_id, objective_id, type)
    NARRATIVES.find do |narrative|  
      narrative.pair_id[:adventure_id] == adventure_id &&
      narrative.pair_id[:objective_id] == objective_id &&
      narrative.type == type 
    end
  end
end

app/models/objective.rb
class Objective
  attr_accessor :title, :expected_output, :pair_id
  def initialize(adventure_id, id, title)
    @title = title
    @pair_id = {
                adventure_id: adventure_id,
                objective_id: id
               }
end
  def self.find(adventure_id, objective_id)
    [
     Objective.new('1', '1', 'Objective 1'),
     Objective.new('1', '2', 'Objective 2'),
     Objective.new('1', '3', 'Objective 3'),
     Objective.new('2', '1', 'Objective 1'),
     Objective.new('2', '2', 'Objective 2'),
     Objective.new('2', '3', 'Objective 3')
    ].find { |objective| objective.pair_id[:objective_id].to_i == objective_id.to_i && objective.pair_id[:adventure_id].to_i == adventure_id.to_i }
  end

  def ==(other)
    @pair_id == other.pair_id &&
   # @adventure_id == other.adventure_id &&
    @title == other.title &&
    @expected_output == other.expected_output
  end
# maps ids for find method
  GET_301 = 1

end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  include ApplicationHelper
  def story
    @adventure = Adventure.find(params[:id])
  end
  def update
    render plain: evaluate(params[:ripl_input])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def find_adventure_and_objective
    @adventure = Adventure.find(params[:adventure_id])
    @objective = Objective.find(params[:adventure_id], params[:id])
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  def http
  end

  def math
  end

  def time
  end

  def database
  end

  def exceptions
  end

  def read
  end

  def dsl
  end

  def gui
  end

  def commandline
  end

  def patterns
  end

  def methods
  end

  def threads
  end

  def core
  end

  def parsers
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController

  def learn
    @objective = Objective.find(params[:adventure_id], params[:id])
    @adventure = Adventure.find(params[:adventure_id])
  end

  def review
    @ripl_output=evaluate('Net::HTTP.get_response(URI("http://prettyp.herokuapp.com"))')
    @adventure = Adventure.find(params[:adventure_id])
    @objective = Objective.find(params[:adventure_id], params[:id])
  end

  def correct?
    @ripl_output.class.name.include? 'Net::HTTPMovedPermanently'
  end

  def repl
    @ripl_output=evaluate(params[:ripl_input])
    if meow?
      redirect_to learn_adventure_objective_path(1,2)
    elsif correct?
      redirect_to review_adventure_objective_path(1,1)
    else
      learn
      render :learn
    end
  end

  private

  def evaluate(params)
    ::Ripl.shell.eval_input(params)
  end

  def meow?
    params[:ripl_input].downcase.include? "meow"
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def prettyp
    head 301
  end
end

app/controllers/stdlib_controller.rb
class StdlibController < ApplicationController

  def chapters
  end

  def about
  end

  def team
  end

  def mobbing
  end

  def agile
  end

  def testing
  end

  def rgsoc
  end

  def userstories
  end

  def goals
  end

end

app/controllers/webtest_controller.rb
class WebtestController < ApplicationController

  def index
    if params[:user_input] == "meow"
       redirect_to "http://www.pinterest.com" 
    else
      render text: ::Ripl.shell.eval_input(params[:user_input])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/webtest_helper.rb
module WebtestHelper
=begin
 require 'ripl'
  object = Ripl::Shell
  puts object.eval_input("2+2")
=end
end

app/views/adventures/show.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <%= render partial: "shared/adventure_title" %>
      <p>The curious cat <br />
       Falling down down down the well <br />
       Cuddy needs your help!
      </p>
      <p>Oh No! Cuddy ran ahead of Mr. Chips and fell down a well. It is very dark inside the well. </p>

      <p>Cuddy finds a tin can with a string leading to the top of the well. He needs your help to place the call <small> (he thinks the phone works).</small></p>
      <p>Let’s try to call Cuddy’s agent, PrettyP.</p>

      <%= link_to "Continue", adventure_objective_path(1,1), class: "btn btn-success btn-adventure" %>

    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("well.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/adventures/story.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <%= render partial: "shared/adventure_title" %>
      <p>The curious cat <br />
       Falling down down down the well <br />
       Cuddy needs your help!
      </p>
      <p>Oh No! Cuddy ran ahead of Mr. Chips and fell down a well. It is very dark inside the well. </p>

      <p>Cuddy finds a tin can with a string leading to the top of the well. He needs your help to place the call <small> (he thinks the phone works).</small></p>
      <p>Let’s try to call Cuddy’s agent, PrettyP.</p>

      <%= link_to "Continue", learn_adventure_objective_path(1,1), class: "btn btn-success btn-adventure" %>

    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("well.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/commandline.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Command Line Tools</h2>
      <%= render partial: "library/commandline" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/core.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Core Ruby Tools</h2>
      <%= render partial: "library/core" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/dsl.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>DSL</h2>
      <%= render partial: "library/dsl" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/encoding.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Encoding - Compression</h2>
      <%= render partial: "library/encoding" %>
    </div>

    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("well.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/exceptions.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Exceptions-Debugging-Testing</h2>
      <%= render partial: "library/exceptions" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("6-cmath.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/gui.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>GUI</h2>
      <%= render partial: "library/gui" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/methods.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Methods</h2>
      <%= render partial: "library/methods" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/objective2.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Adventure 1</h2>
      <h3>Objective 2</h3>

      <p>Oh no. Pretty P. moved. Cuddy needs your help. It is getting dark. </p>
      <p>Try calling Cuddy's friend Shelly.</p> 
      <p>Type in this code:</p>

      <div class='well'><code class="code-example">Net::HTTP.get_response(URI('http://shely.herokuapp.com'))</code></div>

      <p class='psst'>( Psst: Don’t just copy and paste it; type it in. It's the best way to really learn. )</p>
    </div>
    <div class="col-xs-6 pull-right outline">
      <div class="left replbox">
        <%= form_tag review_adventure_objective_path(1, 1) do %>
          <%= text_field_tag :ripl_input, @ripl_output, class: "inputform", placeholder: '>>' %>
          <%= submit_tag "submit", class: "btn btn-success btn-adventure" %>
        <% end %>
      </div>
      <div class="pull-left instructions">
        <p>enter / return - Submit code</p>
        <p>next - Move to the next lesson</p>
        <p>back - Return to previous lesson</p>
      </div> 
      <div class="smallpics pull-left">
        <%= image_tag("404.jpg") %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/objective3.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Adventure 1</h2>
      <h3>Objective 3</h3>

      <p>Shelly, Shelly, Shelly. Where are you?</p>
      <p>Cuddy is getting hungry, tired and scared.</p>
      <p>When you get an error, the first and the best, the main thing to do is to READ THE ERROR. This can be hard at times beacuase on first look it might seem like you broke something. Don't worry, it's just the computer talking to you and telling you what is wrong. (Now you can see why computers don't get a lot of dates.)
      <p>Take your time, read the error. Find the part that is trying to tell you something. Your computer really wants to help you and Cuddy really wants to get out of that hole. 
      <p>Check your code for errors and TRY AGAIN. :)</p>
      <p>Think of it as a game.</p>
      <div class='well'><code class="code-example">Net::HTTP.get_response(URI('http://shelly.herokuapp.com'))</code></div>

    </div>
    <div class="col-xs-6 pull-right outline">
      <div class="left replbox">
        <%= form_tag review_adventure_objective_path(1, 1) do %>
          <%= text_field_tag :ripl_input, @ripl_output, class: "inputform", placeholder: '>>' %>
          <%= submit_tag "submit", class: "btn btn-success btn-adventure" %>
        <% end %>
      </div>
      <div class="pull-left instructions">
        <p>enter / return - Submit code</p>
        <p>next - Move to the next lesson</p>
        <p>back - Return to previous lesson</p>
      </div> 
      <div class="smallpics pull-left">
        <%= image_tag("200.jpg") %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/parsers.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Parsers</h2>
      <%= render partial: "library/parsers" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/patterns.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Patterns</h2>
      <%= render partial: "library/patterns" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/read.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>READ & WRITE - <small>STRING/IO</small></h2>
      <%= render partial: "library/read" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("read.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/threads.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Threads & Server Processes</h2>
      <%= render partial: "library/threads" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catpicnic.png", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/chapters/time.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>Time - Date</h2>
      <%= render partial: "library/time" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("catclock.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <p>
        If you’re new to programming, Ruby is a great introduction. If you’re looking to brush up on your library knowledge, you’re also in the right place. Ruby is flexible, powerful, and easy to read.
      </p>
      <p>  
        The Ruby Standard Library is a set of tools included in the Ruby programming language that are incredibly useful. Many developers and gems use them often. You may have already used the libraries without knowing.
      </p>
      <p>  
  Over the next few adventures, you’ll get to know some of the popular Ruby libraries.  Knowing these can help you program a robot, rig your house to dim the lights, or build a site to sell your homemade (probably poisonous) kombucha. 
      </p>
      <%= link_to "Start Adventure 1", story_adventure_path(1), class: "btn btn-success btn-adventure" %>
    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("adventure-one-intro.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<h1> Feats of Daring <small>with the Ruby Standard Library</small></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Featsofdaring</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/library/_commandline.html.erb
<ul>
  <li> <%= link_to "IRB", "http://ruby-doc.org/stdlib-2.1.2/libdoc/irb/rdoc/index.html" %></li>
    <p class= "libraries">Interactive Ruby command-line tool for REPL (Read Eval Print Loop)</p>

  <li> <%= link_to "RDoc", "http://ruby-doc.org/stdlib-2.1.2/libdoc/rdoc/rdoc/index.html" %></li>
    <p class= "libraries">Produces HTML and command-line documentation for Ruby</p>

  <li> <%= link_to "OptParse", "http://ruby-doc.org/stdlib-2.1.2/libdoc/optparse/rdoc/index.html" %></li>
    <p class= "libraries">Ruby-oriented class for command-line option analysis</p>

  <li> <%= link_to "GetoptLong", "http://ruby-doc.org/stdlib-2.1.2/libdoc/getoptlong/rdoc/index.html" %></li>
    <p class= "libraries">Parse command line options similar to the GNU C getopt_long</p>

  <li> <%= link_to "PTY", "http://ruby-doc.org/stdlib-2.1.2/libdoc/pty/rdoc/index.html" %></li>
    <p class= "libraries">Creates and manages pseudo terminal</p>

  <li> <%= link_to "Win32Ole", "http://ruby-doc.org/stdlib-2.1.2/libdoc/win32ole/rdoc/index.html" %></li>
    <p class= "libraries">A helper class for windows OLE, (Object Linking and Embedding) which is used to control other programs like excel, etc.</p>

  <li> <%= link_to "un", "http://ruby-doc.org/stdlib-2.1.2/libdoc/un/rdoc/index.html" %></li>
    <p class= "libraries">Utilities to replace common UNIX commands</p>
</ul>

app/views/library/_core.html.erb
<ul>
  <li> <%= link_to "IRB", "http://ruby-doc.org/stdlib-2.1.2/libdoc/irb/rdoc/index.html" %></li>
    <p class= "libraries">Interactive Ruby Shell</p>

  <li> <%= link_to "ERB", "http://ruby-doc.org/stdlib-2.1.2/libdoc/erb/rdoc/index.html" %></li>
    <p class= "libraries">An easy to use but powerful templating system for Ruby</p>

  <li> <%= link_to "Gem", "http://ruby-doc.org/stdlib-2.1.2/libdoc/gem/rdoc/index.html" %></li>
    <p class= "libraries">Package management framework for Ruby</p>

  <li> <%= link_to "DL", "http://ruby-doc.org/stdlib-2.1.2/libdoc/dl/rdoc/index.html" %></li>
    <p class= "libraries">Provides a wrapper for the UNIX dlopen() library</p>

  <li> <%= link_to "Fiddle", "http://ruby-doc.org/stdlib-2.1.2/libdoc/fiddle/rdoc/index.html" %></li>
    <p class= "libraries">A libffi wrapper for Ruby</p>
</ul>

app/views/objectives/learn.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <%= render partial: "shared/adventure_title" %>
      <%= render partial: "shared/objective_title" %>

      <p>On the right, in the terminal window try placing a call to PrettyP.</p>

      <p>Type in this code:</p>
      <div class='well'><code class="code-example">
      <%= t("adventure_#{params[:adventure_id]}_net_http.objective_#{params[:id]}.code_to_submit")%></code></div>

      <p class='psst'>( Psst: Don’t just copy and paste it; type it in. It's the best way to really learn. )</p>
    </div>
    <div class="col-xs-6 pull-right outline">
      <div class="left replbox">
        <%= form_tag repl_adventure_objective_path(1, 1) do %>
          <%= text_field_tag :ripl_input, @ripl_output, class: "inputform", placeholder: '>>' %>
          <%= submit_tag "submit", class: "btn btn-success btn-adventure" %>
        <% end %>
      </div>
      <div class="pull-left instructions">
        <p>enter / return - Submit code</p>
        <p>next - Move to the next lesson</p>
        <p>back - Return to previous lesson</p>
      </div>
      <div class="smallpics pull-left">
        <%= image_tag("well-sm.jpg") %>
      </div>
    </div>
  </div>
</div>

app/views/objectives/review.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <%= render partial: "shared/adventure_title" %>
      <%= render partial: "shared/objective_title" %>

      <%= simple_format t("adventure_#{params[:adventure_id]}_net_http.objective_#{params[:id]}.review")%>
    </div>
    <div class="col-xs-6 pull-right outline">
      <div class="left replbox">
        <%= form_tag repl_adventure_objective_path do %>
          <%= text_field_tag :ripl_input, @ripl_output, class: "inputform" %>
          <%= submit_tag "submit", class: "btn btn-success btn-adventure" %>
        <% end %>
      </div>
      <div class="pull-left instructions">
        <p>enter / return - Submit code</p>
        <p>next - Move to the next lesson</p>
        <p>back - Return to previous lesson</p>
      </div>
      <div class="smallpics pull-left">
        <%= image_tag("301.jpg") %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_adventure_title.html.erb
<h2><%= @adventure.title%></h2>

app/views/shared/_navbar.html.erb
<!-- http://www.tutorialspoint.com/bootstrap/bootstrap_navbar.htm -->

<nav class="navbar navbar-default" role="navigation">
  <!-- <div class="navbar-header">
    <a class="navbar-brand" href="#">TutorialsPoint</a>
  </div> -->
  <div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", root_path %></li>
      <li><%#= link_to "About The Standard Librarians", '#' %></li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Adventures<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "HTTP Protocol - Story", story_adventure_path(1) %></li>
          <li><%= link_to "HTTP Protocol - Objective 1", learn_adventure_objective_path(1,1) %></li>
          <li><%= link_to "HTTP Protocol - Objective 2", chapters_objective2_path %></li>
          <li><%= link_to "HTTP Protocol - Objective 3", chapters_objective3_path %></li>
        </ul>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Chapters<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "HTTP Protocol",          chapters_http_path %></li>
          <li><%= link_to "Encoding - Compression", chapters_encoding_path %></li>
          <li><%= link_to "Math",                   chapters_math_path %></li>
          <li><%= link_to "Time - Date",            chapters_time_path %></li>
          <li><%= link_to "Database",               chapters_database_path %></li>
          <li><%= link_to "Exceptions-Debugging-Testing", chapters_exceptions_path %></li>
          <li><%= link_to "Read & Write - IO",      chapters_read_path %></li>
          <li><%= link_to "DSL",                    chapters_dsl_path %></li>
          <li><%= link_to "GUI",                    chapters_gui_path %></li>
          <li><%= link_to "Commandline Tools",      chapters_commandline_path %></li>
          <li><%= link_to "Patterns",               chapters_patterns_path %></li>
          <li><%= link_to "Methods",                chapters_methods_path %></li>
          <li><%= link_to "Threads & Server Processes", chapters_threads_path %></li>
          <li><%= link_to "Core Ruby Tools",        chapters_core_path %></li>
        </ul>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          The Standard Librarians <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "About",        stdlib_about_path %></li>
          <li><%= link_to "The Team",     stdlib_team_path %></li>
          <li><%= link_to "Mobbing",      stdlib_mobbing_path %></li>
          <li><%= link_to "Agile",        stdlib_agile_path %></li>
          <li><%= link_to "Testing",      stdlib_testing_path %></li>
          <li><%= link_to "RGSoC",        stdlib_rgsoc_path %></li>
          <li><%= link_to "User Stories", stdlib_userstories_path %></li>
          <li><%= link_to "Future Goals", stdlib_goals_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/stdlib/chapters.html.erb
<%= render partial: "shared/navbar" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 left outline">
      <h2>CHAPTERS</h2>

      <%= link_to "Continue", adventure_objective_path(1,1), class: "btn btn-success btn-adventure" %>

    </div>
    <div class="col-xs-6 right outline top-padding">
      <%= image_tag("2-cats.jpg", class: "large-illustration") %>
    </div>
  </div>
</div>